project_id = "bopiuworvbjsowfjbmfx"

[functions.process-reminders]
verify_jwt = false

[functions.test-push]
verify_jwt = true

[functions.test-push-ios]
verify_jwt = true

[functions.delete-account]
verify_jwt = true
